import { ReduxProvider } from '@/globalRedux/Provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full`}>
        <ReduxProvider>
          <header>
            <Link href="/signup">Sign Up</Link>
            <Link href="/login">Login</Link>
            <Link href="/bookings">Bookings</Link>
            </header>
        {children}</ReduxProvider>
      </body>
    </html>
  );
}
